# Generated by Django 3.2.4 on 2021-09-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='contents',
            field=models.TextField(),
        ),
    ]
