# Generated by Django 3.2.5 on 2021-09-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='contents',
            field=models.CharField(max_length=2048),
        ),
    ]
